# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57854ccdf72d7e11738a1b887b32fed9481017f76027b59c1a07bbf603e6bf679160a1816469c1e39fa21d60f4b49f971265c61ef2a2ccfbf4ae0578438ee386

test:
  secret_key_base: 3261a2572cc96b151fd8fb66174247e4b3251e82bd24651f60e2be4c496b2d2e89183da8efa98ac259dd5e725247887d7ff2e35d9dbf65298df1d7a04f245644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
